### ISSUE TITLE
URIs expressed as strings

### ISSUE THREAD

**Issue by andrawaag** [ejp-rd-vp/DistributedAnalysisDemonstrator#2]
In the ttl files in the MONARCH_PHENOPACKET_STORE_DATA some of the URIs are expressed as strings and not as URIs. 
See for example:
https://github.com/ejp-rd-vp/DistributedAnalysisDemonstrator/blob/4c7a8734bd45bb8d0480ec52ce44941bdef4f991/MONARCH_PHENOPACKET_STORE_DATA/PMID_26467218_individual10-Kraouaetal23.ttl#L24

If have fixed it manually in PMID_26467218_individual1-DeFilippietal20.ttl.

@rosazwart @NuriaQueralt Do you know if this can be fixed at the source or do we need to do it in all files manually?

**Comment by rosazwart** [comment]
I indeed had problems with expressing the URIs in URIs instead of literal string values. I will look into it again today. Hopefully I can come up with something that will solve this issue.

**Comment by rosazwart** [comment]
I indeed had problems with expressing the URIs in URIs instead of literal string values. I will look into it again today. Hopefully I can come up with something that will solve this issue.

**Comment by rosazwart** [comment]
The RDF files in the folders ([HAMLET](https://github.com/ejp-rd-vp/DistributedAnalysisDemonstrator/tree/main/HAMLET_DATA), [PHENOPACKET-STORE](https://github.com/ejp-rd-vp/DistributedAnalysisDemonstrator/tree/main/MONARCH_PHENOPACKET_STORE_DATA)) are now containing the URIs expressed as URIs instead of string values. There was an issue in the YARRRML syntax. Now that it is fixed, the RDF files will have URIs in the correct expression format.

Let me know if you find something else that needs to be improved! Will close this issue for now.
